#!/usr/local/bin/zsh
# docker build and remove

dbr () {
    DOCKERFILE=$1

    # remove old non running containers
    docker ps -a | awk '/Exited/ {print $1}' | xargs docker rm >/dev/null 2>&1
    # docker rm $(docker ps -a -q)

    # build and return id on stdout
    docker build $DOCKERFILE | tail -1 | awk '{print $3}'
}
