#!/bin/bash
# Find instances based on name

ec2 () {
    if [ -n "$1" ]; then
        aws ec2 describe-tags --filters "Name=key,Values=Name" "Name=value,Values=*$1*"
    else
        echo "need something to search: \"$1\" isn't good enough"
    fi
}
