alias reload!='. ~/.zshrc'
alias ls='ls -G'
alias cd..="cd .."
alias l="ls -al"
alias lp="ls -p"
alias h='history'
alias mkdir='mkdir -p'
alias la='ls -a'
alias ll='ls -l'
alias ..='cd ..'
alias ...='cd ../..'
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ts="tig status"